version: "3.8"

services:
  api-rest:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - postgres
    environment:
      - DATABASE=postgres
    ports:
      - "4000:4000"

  postgres:
    container_name: "postgres_container"
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=pgadmin
      - POSTGRES_PASSWORD=pg123
      - POSTGRES_DB=mande_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
