name: Actions

on:
  push:
    branches: [pruebasFuncionales]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm ci --prefix forme-app

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 libappindicator1 libindicator7

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N "https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Configure Chrome sandboxing
        run: |
          sudo chown root:root /opt/google/chrome/chrome-sandbox
          sudo chmod 4755 /opt/google/chrome/chrome-sandbox
          sudo chown root:root /opt/google/chrome/chrome-sandbox
          sudo chmod 4755 /opt/google/chrome/chrome-sandbox
          sudo cat /opt/google/chrome/chrome-sandbox
          sudo ls -ld /opt/google/chrome/chrome-sandbox

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app

      - name: Build Frontend Docker image
        working-directory: forme-app
        run: docker build -t front -f Dockerfile .

      - name: Build Backend Docker image
        working-directory: backend
        run: docker build -t back -f Dockerfile .
