name: Actions

on:
  push:
    branches: [pruebasFuncionales]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm i --force --prefix forme-app

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 libappindicator1 libindicator7
          sudo apt-get install -y libasound2 libatk-bridge2.0-0 libatk1.0-0 libcups2 libdrm2 libgbm1 libgtk-3-0 libnspr4 libnss3 libx11-xcb1 libxcb-dri3-0 libxcomposite1 libxdamage1 libxfixes3 libxkbcommon0 libxrandr2 libxshmfence1 libxtst6

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/

      - name: Configure Chrome sandboxing
        run: |
          sudo sysctl -w kernel.unprivileged_userns_clone=1

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app

      - name: Build Frontend Docker image
        working-directory: forme-app
        run: docker build -t front -f Dockerfile .

      - name: Build Backend Docker image
        working-directory: backend
        run: docker build -t back -f Dockerfile .