name: Actiones

on:
  push:
    branches: [ main ]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm i --force --prefix forme-app

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app
      
      - name: Imagen front
        run: Docker build -t front -f Dockerfile.forme-app
      
      - name: Imagen Back
        run: Docker build -t back -f Dockerfile.backend 
        
