name: Actiones

on:
  push:
    branches: [ main ]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: "latest"
          
      - name: Install ChromeDriver
        run: |
          LATEST_CHROMEDRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)
          curl -sS -o chromedriver_linux64.zip "https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm i --force --prefix forme-app
      
      # - name: Install Chrome
      #   uses: browser-actions/setup-chrome@latest
        # run: chrome --version

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app

      - name: Build Frontend Docker image
        working-directory: forme-app
        run: docker build -t front -f Dockerfile .
      
      - name: Build Backend Docker image
        working-directory: backend
        run: docker build -t back -f Dockerfile .
        
