name: Actiones

on:
  push:
    branches: [pruebasFuncionales]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm i --force --prefix forme-app

      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 libappindicator1 libindicator7

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(google-chrome-stable --version | grep -oP '(?<=Google Chrome )[^.]+')
          wget -q "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROMEDRIVER_VERSION"/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip -d chromedriver
          sudo mv chromedriver/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app

      - name: Build Frontend Docker image
        working-directory: forme-app
        run: docker build -t front -f Dockerfile .

      - name: Build Backend Docker image
        working-directory: backend
        run: docker build -t back -f Dockerfile .
