name: Actions

on:
  push:
    branches: [pruebasFuncionales]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm i --force --prefix forme-app

      - name: Set up Selenium WebDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget curl unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
      
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
      
        env:
          CHROME_BIN: /usr/bin/google-chrome


      - name: Install dependencies for Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y libxss1 libappindicator1 libindicator7
          sudo apt-get install -y wget curl unzip
          wget -N https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f

      - name: Install ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip
          wget -N https://chromedriver.storage.googleapis.com/$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
          sudo unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app

      - name: Build Frontend Docker image
        working-directory: forme-app
        run: docker build -t front -f Dockerfile .

      - name: Build Backend Docker image
        working-directory: backend
        run: docker build -t back -f Dockerfile .
