name: Actions

on:
  push:
    branches: [main]

jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies on Backend folder
        run: npm ci --prefix backend

      - name: Run tests on Backend folder
        run: npm run test --prefix backend

      - name: Install dependencies on Frontend folder
        run: npm i --force --prefix forme-app

      - name: Set up Selenium WebDriver
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
        env:
            CHROME_BIN: /usr/bin/google-chrome

      - name: Run tests on frontend folder
        run: npm run test --prefix forme-app

      - name: Deploy to Vercel
        if: ${{ success() }}
        run: |
          cd forme-app
          npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}

          